apiVersion: v1
kind: PersistentVolume
metadata:
  name: fe-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/fe

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fe-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: t3-fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: t3-fe-container
          image: teamark/hng-docker-task1:hng-task1-fe
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: fe-volume
              mountPath: /data/
          envFrom:
            - configMapRef:
                name: t3-fe-configmap
      volumes:
        - name: fe-volume
          persistentVolumeClaim:
            claimName: fe-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: t3-fe-service
spec:
  type: NodePort
  selector:
    app: fe
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300